
os: linux
language: python
python: "3.6"

matrix:
  include:
    - dist: bionic
    - dist: xenial
    - dist: trusty

install:
  - sudo -H pip install -U pip setuptools wheel
  - sudo -H pip install -U scons
  - sudo apt-get install gcc g++ libfreetype6-dev libglib2.0-dev libcairo2-dev
  - sudo apt-get install pkg-config ragel gtk-doc-tools gobject-introspection
  - sudo apt-get install libicu-dev icu-devtools libgraphite2-dev libgirepository1.0-dev dbus 

script:
  - cd ${TRAVIS_BUILD_DIR}
  - scons --have-freetype --have-graphite2 --have-glib --have-icu --have-gobject --have-introspection --build-tests
